services:
  postgres:
    image: postgres:15
    container_name: car_shop_db
    environment:
      POSTGRES_USER: car_shop_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: car_shop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - car_shop_network

volumes:
  postgres_data:

networks:
  car_shop_network:
    driver: bridge
