package ru.ylab.hw1.repository.impl;

import lombok.extern.slf4j.Slf4j;
import ru.ylab.hw1.config.DatabaseConfig;
import ru.ylab.hw1.dto.Car;
import ru.ylab.hw1.exception.DataAccessException;
import ru.ylab.hw1.repository.AbstractRepository;
import ru.ylab.hw1.repository.CarRepository;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * Implementation of the {@link CarRepository} interface for performing CRUD operations on {@link Car} entities.
 * This class interacts with a PostgreSQL database to manage car data.
 */
@Slf4j
public class CarRepositoryImpl extends AbstractRepository implements CarRepository {

    /**
     * Saves a new car to the database. The car's VIN number is generated by the database and
     * returned to the car entity. If an error occurs during the operation, the transaction is rolled back.
     *
     * @param car the car entity to be saved
     * @return the saved car entity with the generated VIN number
     * @throws DataAccessException if there is an error accessing the database
     */
    public Car save(Car car) {
        String sql = "INSERT INTO entity_schema.car (car_vin_number, brand, model, year, price, condition) VALUES (?, ?, ?, ?, ?, ?) RETURNING car_vin_number";

        Connection connection = null;
        try {
            connection = DatabaseConfig.getConnection();
            connection.setAutoCommit(false);

            try (PreparedStatement statement = connection.prepareStatement(sql)) {
                createStatement(car, statement);

                ResultSet resultSet = statement.executeQuery();
                if (resultSet.next()) {
                    String vin = resultSet.getString("car_vin_number");
                    car.setVinNumber(vin);
                    log.info("Car with VIN {} has been saved", vin);
                }

                connection.commit();
            } catch (SQLException e) {
                rollbackConnection(connection);
                log.error("Error creating car with VIN: {}", car.getVinNumber(), e);
            }
        } catch (SQLException e) {
            log.error("Database error when saving car", e);
            throw new DataAccessException("Error saving car", e);
        } finally {
            closeConnection(connection);
        }

        return car;
    }

    /**
     * Updates an existing car in the database. If no car with the given VIN is found, a warning is logged.
     * If an error occurs during the operation, the transaction is rolled back.
     *
     * @param car the car entity with updated information
     * @throws DataAccessException if there is an error accessing the database
     */
    public void edit(Car car) {
        String sql = "UPDATE entity_schema.car SET brand = ?, model = ?, year = ?, price = ?, condition = ? WHERE car_vin_number = ?";

        Connection connection = null;

        try {
            connection = DatabaseConfig.getConnection();
            connection.setAutoCommit(false);

            try (PreparedStatement statement = connection.prepareStatement(sql)) {
                createStatement(car, statement);

                int rowUpdated = statement.executeUpdate();

                if (rowUpdated == 0) {
                    log.warn("Not found car with VIN: {}", car.getVinNumber());
                } else {
                    log.info("Car with VIN {} was updated successfully.", car.getVinNumber());
                }

                connection.commit();
            } catch (SQLException e) {
                rollbackConnection(connection);
                log.error("Error updating car with VIN: {}", car.getVinNumber(), e);
            }
        } catch (SQLException e) {
            log.error("Database error when updating car", e);
            throw new DataAccessException("Error updating car", e);
        } finally {
            closeConnection(connection);
        }
    }

    /**
     * Deletes a car from the database by its VIN number. If an error occurs during the operation,
     * the transaction is rolled back.
     *
     * @param vinNumber the VIN number of the car to be deleted
     * @throws DataAccessException if there is an error accessing the database
     */
    public void delete(String vinNumber) {
        String sql = "DELETE FROM entity_schema.car WHERE id = ?";

        Connection connection = null;

        try {
            connection = DatabaseConfig.getConnection();
            connection.setAutoCommit(false);

            try (PreparedStatement statement = connection.prepareStatement(sql)) {
                statement.setString(1, vinNumber);
                statement.executeUpdate();
                log.info("Car with VIN {} was deleted successfully.", vinNumber);

                connection.commit();
            } catch (SQLException e) {
                rollbackConnection(connection);
                log.error("Error deleting car with VIN: {}", vinNumber, e);
            }
        } catch (SQLException e) {
            log.error("Database error when deleting car", e);
            throw new DataAccessException("Error deleting car", e);
        } finally {
            closeConnection(connection);
        }
    }

    /**
     * Retrieves a list of all cars from the database.
     *
     * @return a list of all cars
     */
    public List<Car> findAll() {
        List<Car> cars = new ArrayList<>();
        String sql = "SELECT * FROM entity_schema.car";

        try (Connection connection = DatabaseConfig.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql);
             ResultSet resultSet = statement.executeQuery()) {

            while (resultSet.next()) {
                Car car = new Car();
                car.setVinNumber(resultSet.getString("car_vin_number"));
                car.setBrand(resultSet.getString("brand"));
                car.setModel(resultSet.getString("model"));
                car.setYear(resultSet.getInt("year"));
                car.setPrice(resultSet.getDouble("price"));
                car.setCondition(resultSet.getString("condition"));

                cars.add(car);
            }
        } catch (SQLException e) {
            log.error("Error fetching cars", e);
        }
        return cars;
    }

    /**
     * Retrieves a car from the database by its VIN number.
     *
     * @param vinNumber the VIN number of the car to be retrieved
     * @return an {@link Optional} containing the car if found, or an empty {@link Optional} if not
     */
    public Optional<Car> findByVin(String vinNumber) {
        String sql = "SELECT brand, model, year, price, condition FROM entity_schema.car WHERE car_vin_number = ?";

        try (Connection connection = DatabaseConfig.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {

            statement.setString(1, vinNumber);

            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    String brand = resultSet.getString("brand");
                    String model = resultSet.getString("model");
                    int year = resultSet.getInt("year");
                    double price = resultSet.getDouble("price");
                    String condition = resultSet.getString("condition");

                    Car car = new Car(vinNumber, brand, model, year, price, condition);
                    return Optional.of(car);
                }
            }

        } catch (SQLException e) {
            log.error("Error fetching car with VIN: {}", vinNumber, e);
        }

        return Optional.empty();
    }

    /**
     * Fills a {@link PreparedStatement} with the attributes of a {@link Car} entity.
     *
     * @param car       the car entity
     * @param statement the prepared statement to fill
     * @throws SQLException if there is an error setting a parameter in the statement
     */
    private void createStatement(Car car, PreparedStatement statement) throws SQLException {
        statement.setString(1, car.getVinNumber());
        statement.setString(2, car.getBrand());
        statement.setString(3, car.getModel());
        statement.setInt(4, car.getYear());
        statement.setDouble(5, car.getPrice());
        statement.setString(6, car.getCondition());
    }
}
