spring:
  application:
    name: audit-logging
  datasource:
    url: jdbc:postgresql://localhost:5432/car_shop_db
    username: car_shop_user
    password: password
    name: car_shop_db
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog.ml
